# Phase 2: BLE 功能已修复
# 修复: sdk/CMakeLists.txt 现在支持 BUILD_WIRELESS_FROM_SOURCE 条件
set(BLE_ENABLE ON CACHE BOOL "KB" FORCE)
set(ESB_ENABLE OFF CACHE BOOL "KB" FORCE)

# Phase 1: 启用调试输出 (UART2/PB23, 115200 baud)
set(DEBUG_UART_ENABLE ON CACHE BOOL "KB" FORCE)

message(STATUS "Obey65 default keymap: BLE=${BLE_ENABLE}, ESB=${ESB_ENABLE}, DEBUG_UART=${DEBUG_UART_ENABLE}")