set(MOUSE_ENABLE ON CACHE BOOL "KB" FORCE)
set(NKRO_ENABLE ON CACHE BOOL "KB" FORCE)
set(ENCODER_ENABLE OFF CACHE BOOL "KB" FORCE)
set(ENCODER_MAP_ENABLE OFF CACHE BOOL "KB" FORCE)
set(VIA_ENABLE ON CACHE BOOL "KB" FORCE)
set(BOOTMAGIC_ENABLE ON CACHE BOOL "KB" FORCE)
set(GRAVE_ESC_ENABLE ON CACHE BOOL "KB" FORCE)
set(COMMAND_ENABLE ON CACHE BOOL "KB" FORCE)
set(RGBLIGHT_ENABLE OFF CACHE BOOL "KB" FORCE)
set(RGB_MATRIX_WS2812 ON CACHE BOOL "KB" FORCE)
set(RGB_MATRIX_ENABLE ON CACHE BOOL "KB" FORCE)
set(AUXILIARY_RGB_ENABLE OFF CACHE BOOL "KB" FORCE)
set(CIE1931_CURVE OFF CACHE BOOL "KB" FORCE)
set(SPLIT_KEYBOARD OFF CACHE BOOL "KB" FORCE)
set(OLED_ENABLE OFF CACHE BOOL "KB" FORCE)

# set(RGBLIGHT_DRIVER "WS2812" CACHE STRING "KB" FORCE)
set(RGB_MATRIX_DRIVER "WS2812" CACHE STRING "KB" FORCE)
set(SPLIT_TRANSPORT "custom" CACHE STRING "KB" FORCE)
set(WS2812_DRIVER "pwm" CACHE STRING "KB" FORCE)
set(WS2812_PWM_DRIVER 2 CACHE INTERNAL "KB" FORCE)
set(OLED_DRIVER "SSD1306" CACHE STRING "KB" FORCE)
set(EEPROM_DRIVER "custom" CACHE STRING "KB" FORCE)

# set(CUSTOM_MATRIX "${CMAKE_CURRENT_LIST_DIR}/matrix.c" CACHE STRING "KB" FORCE)
set(WS2812_DRIVER_REQUIRED ON CACHE BOOL "KB" FORCE)
set(USB_ENABLE ON CACHE BOOL "KB" FORCE)
set(RGB_RAW_ENABLE ON CACHE BOOL "KB" FORCE)
# 无线功能默认关闭，由 keymap/rules.cmake 按需启用
# set(BLE_ENABLE ON CACHE BOOL "KB" FORCE)
# set(ESB_ENABLE ON CACHE BOOL "KB" FORCE)

# 添加自定义WS2812源文件
set(CUSTOM_WS2812_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/ws2812_tmr2.c"
)

# 调试功能 - 通过 UART2 (PB23) 输出调试信息
# 在 keymap/rules.cmake 中启用: set(DEBUG_UART_ENABLE ON)
option(DEBUG_UART_ENABLE "Enable debug UART output on PB23" OFF)
if(DEBUG_UART_ENABLE)
    add_definitions(-DDEBUG_UART_ENABLE)
    list(APPEND QMK_PORTING_SOURCES "${CMAKE_CURRENT_LIST_DIR}/debug_uart.c")
    message(STATUS "Obey65: Debug UART enabled (TX=PB23, 115200 baud)")
endif()

# 无线模式管理框架 (Phase 1.2)
# 始终包含，为 Phase 2/3 无线功能做准备
list(APPEND QMK_PORTING_SOURCES "${CMAKE_CURRENT_LIST_DIR}/wireless_mode.c")

# 电池管理 (Phase 1.3)
# 提供 obey65 专用电池配置和状态查询
list(APPEND QMK_PORTING_SOURCES "${CMAKE_CURRENT_LIST_DIR}/battery.c")

# 电源管理框架 (Phase 1.4)
# 自动休眠、唤醒管理
list(APPEND QMK_PORTING_SOURCES "${CMAKE_CURRENT_LIST_DIR}/power_mode.c")

# 状态指示器 (Phase 4.3)
# RGB LED 模式/电量/连接状态指示
list(APPEND QMK_PORTING_SOURCES "${CMAKE_CURRENT_LIST_DIR}/status_indicator.c")

# set(ESB_ROLE "keyboard" CACHE STRING "KB") 